FROM ghcr.io/mlflow/mlflow:latest AS base
RUN pip install --no-cache-dir psycopg2-binary boto3

# Copy and make the entrypoint executable
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Production stage (last stage)
FROM base AS production
ENTRYPOINT ["/entrypoint.sh"]
