services:
  mlflow:
    build:
      context: .
      target: mlflow
    image: mlflow-server:latest
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MLFLOW_BACKEND_URI=${MLFLOW_BACKEND_URI}
      - MLFLOW_S3_BUCKET=${MLFLOW_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/opt/app
  prefect:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - prefect_home:/home/app/.prefect

  pipeline:
    build:
      context: .
      target: pipeline
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/opt/app
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
      - PREFECT_API_URL=http://host.docker.internal:4200/api
      - PYTHONUNBUFFERED=1
      - PREFECT_LOGGING_LEVEL=INFO
      - RICH_FORCE_TERMINAL=1
      - TERM=xterm-256color
      - FORCE_COLOR=1
    depends_on:
      mlflow:
        condition: service_started
      prefect:
        condition: service_started

  app:
    build:
      context: .
      target: app
    ports:
      - "8501:8501"
    volumes:
      - ~/.cache/pip:/root/.cache/pip:rw
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

volumes:
  prefect_home:
