# render.yaml

databases:
  - name: mlflow-db
    plan: free

services:
  - name: mlflow
    type: web
    env: docker
    plan: free

    # 1) Docker context pour buildCommand
    dockerContext: .           # racine du repo
    # (on ne précise plus dockerfilePath, car buildCommand l’indique)

    # 2) Build seulement jusqu'à target "mlflow"
    buildCommand: |
      docker build \
        --target mlflow \
        -f Dockerfile \
        -t mlflow-server:latest \
        .

    # 3) Lancement manuel du MLflow server
    startCommand: |
      # le script ENTRYPOINT est à la racine de l’image
      /entrypoint.sh

    autoDeploy: true
    healthCheckPath: /          # expose le serveur MLflow à /

    envVars:
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
      # (tes AWS_* et MLFLOW_S3_BUCKET restent à ajouter dans l’UI Render)
