databases:
  - name: mlflow-db
    plan: free

services:
  - name: mlflow
    type: web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    environmentGroups:
      - aws-mlflow-secrets
    envVars:
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString

  - name: streamlit
    type: web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    environmentGroups:
      - aws-mlflow-secrets
    envVars:
      - key: MLFLOW_TRACKING_URI
        value: http://mlflow:5000
