# render.yaml

databases:
  - name: mlflow-db
    plan: free

services:
  - name: mlflow
    type: web
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /

    envVars:
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
      - key: MLFLOW_S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false

  - name: streamlit
    type: web
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /

    envVars:
      - key: MLFLOW_TRACKING_URI
        value: http://mlflow:5000
      - key: MLFLOW_S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        sync: false
