databases:
  - name: mlflow-db
    plan: free

services:
  - name: mlflow
    type: web
    env: docker
    plan: free

    # On ne précise plus dockerContext/dockerfilePath :
    buildCommand: |
      docker build \
        --target mlflow \
        -f Dockerfile \
        -t mlflow-server:latest \
        .

    # Render va utiliser cette image et démarrer avec startCommand :
    startCommand: |
      # entrypoint.sh lit déjà MLFLOW_BACKEND_URI et MLFLOW_S3_BUCKET
      ./entrypoint.sh

    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
