# render.yaml

databases:
  - name: mlflow-db
    plan: free

services:
  - name: mlflow
    type: web
    env: docker
    plan: free
    dockerContext: .                  # Contexte = racine du repo
    dockerfilePath: Dockerfile
    dockerBuildArgs:                  # ← on précise la target ici
      - --target
      - mlflow
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
