# render.yaml

databases:
  - name: mlflow-db
    plan: free

services:
  # ──────────────── MLflow Server ─────────────────
  - name: mlflow
    type: web
    env: docker
    plan: free
    # on build l’image jusqu’au target "mlflow"
    buildCommand: |
      docker build \
        --target mlflow \
        -f Dockerfile \
        -t mlflow-server:latest \
        .
    # on utilise l’ENTRYPOINT du Dockerfile (entrypoint.sh)
    startCommand: |
      /entrypoint.sh
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - name: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString

  # ────────────── Streamlit UI ────────────────────
  - name: streamlit
    type: web
    env: docker
    plan: free
    buildCommand: |
      docker build \
        --target app \
        -f Dockerfile \
        -t streamlit-ui:latest \
        .
    startCommand: |
      streamlit run app/app.py \
        --server.address=0.0.0.0 \
        --server.port=8501 \
        --server.headless=true
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - name: MLFLOW_TRACKING_URI
        value: https://<VOTRE_NOM>.onrender.com   # URL publique de votre service MLflow
