databases:
  - name: mlflow-db
    plan: free        # Postgres Free (256 Mo RAM + 256 Mo disque)

services:
  - name: mlflow
    type: web
    env: docker
    plan: free
    dockerContext: .      # Contexte Docker = la racine du repo
    dockerfilePath: Dockerfile
    autoDeploy: true      # Rebuild & redeploy à chaque git push
    healthCheckPath: /    # GET / doit répondre 200
    envVars:
      # 1) Point MLflow vers la base Postgres gérée par Render
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
