# render.yaml
databases:
  - name: mlflow-db
    plan: free        # Postgres Free (256 Mo RAM + 256 Mo disque)

services:
  - name: mlflow
    type: web
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      # 1) Tracking store dans la base Postgres fournie par Render
      - key: MLFLOW_BACKEND_URI
        fromDatabase:
          name: mlflow-db
          property: connectionString
