name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: |
            type=gha,scope=global
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: |
            type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max,scope=global
            type=gha,scope=global,mode=max

  security-scan:
    needs: build-push
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.32.0
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          skip-setup-trivy: true

  smoke-test:
    needs: build-push
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
      - name: Pipeline smoke test
        run: python -m src.run --help || true
