name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with ruff
        run: make lint

      - name: Run tests & collect coverage
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Smoke-test Docker Compose via Makefile
        run: |
          # 1) Start mlflow, prefect and app services
          MAKE_OPTS="" make up &

          # 2) Fetch the container ID for the `app` service
          APP_ID=$(docker compose ps -q app)
          if [ -z "$APP_ID" ]; then
            echo "❌ Could not find the 'app' container"
            make down
            exit 1
          fi

          # 3) Wait for the container to exit (non-zero exit code fails the step)
          echo "⏳ Waiting for the app container ($APP_ID) to finish..."
          docker wait "$APP_ID"

          # 4) Teardown
          make down